export enum StorageKeys {

  USER_ID = "USER_ID",
  USER_ROLE = "USER_ROLE",
  FIELDS_REGEX_VALIDATIONS = "FIELDS_REGEX_VALIDATIONS",

  USER_FIRST_NAME = "USER_FIRST_NAME",
  USER_LAST_NAME = "USER_LAST_NAME",
  USER_EMAIL_ID = "USER_EMAIL_ID",
  USER_LOGIN_TOKEN = "USER_LOGIN_TOKEN",
 
  APP_CONFIG = "APP_CONFIG",
  NAME="NAME",

  TOKEN="TOKEN",
}
